openapi: 3.0.0
info:
  version: 1.0.0
  title: My API
  description: An OpenAPI example API
paths:
  /posts:
    get:
      description: Returns all posts
      tags: ["Posts"]
      operationId: "getPosts"
      responses:
        "200":
          description: Successful response
    post:
      description: Creates a new post
      tags: ["Posts"]
      operationId: "createPost"
      responses:
        "200":
          description: Successful response
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/PostsListResponse"
components:
  schemas:
    PostsListResponse:
      "type": "array"
      "items":
        $ref: "#/components/schemas/Post"
    Post:
      "type": "object"
      "required":
        - "id"
        - "userId"
        - "title"
        - "completed"
      "properties":
        id:
          type: "integer"
        userId:
          type: "integer"
        title:
          type: "string"
        completed:
          type: "string"
